using CombatSolverCli;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Players;
int passed = 0;
void Test(string name, Action test) { test(); passed++; Console.WriteLine("PASS " + name); }
void Reject(Action test) { try { test(); } catch (InvalidOperationException) { return; } throw new Exception("Expected transaction rejection"); }
var player = new Player();
foreach (var pile in Enum.GetValues<PileType>()) player.Piles[pile] = new();
string Key(CardModel c) => $"{c.Id.Entry}:{c.CurrentUpgradeLevel}:{c.State}";
Token Token(CardModel c, int source = 0, int option = 0) => new(c.Id.Entry, c.CurrentUpgradeLevel, Key(c), source, option);
ChoiceTransaction Tx(params Choice[] choices) => new(choices, player, Key);
Choice Choice(string source, params Token[] tokens) => new(source, "unknown", tokens);
var first = new CardModel("A"); var second = new CardModel("A"); var distinct = new CardModel("B");
player.Piles[PileType.Hand].Cards.AddRange([first, second, distinct]);
Test("nonzero identity", () => { using var t = Tx(Choice("Hand", Token(second, 1, 1))); var r = t.BeginRequest("hand", "Hand", "unknown", 1, 1); t.OpenRequest(r, [first, second]); if (!ReferenceEquals(t.Select([first,second],1,1)[0], second)) throw new Exception(); t.CompleteRequest(r,[second]); t.FinishAction(); });
Test("filtered occurrence", () => { using var t = Tx(Choice("Hand", Token(second, 1))); var r=t.BeginRequest("filtered","Hand","unknown",1,1);t.OpenRequest(r,[second]);t.CompleteRequest(r,[second]);t.FinishAction(); });
Test("wrong same-name instance", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first,second]);Reject(()=>t.CompleteRequest(r,[second]));Reject(()=>t.FinishAction());});
Test("state snapshot survives mutation", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);first.State="changed";t.CompleteRequest(r,[first]);t.FinishAction();first.State="base";});
Test("wrong state", () => {using var t=Tx(Choice("Hand",Token(first) with {StateKey="wrong"}));var r=t.BeginRequest("hand","Hand","unknown",1,1);Reject(()=>t.OpenRequest(r,[first]));});
Test("wrong source", () => {using var t=Tx(Choice("Discard",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);Reject(()=>t.OpenRequest(r,[first]));});
Test("wrong effect", () => {using var t=Tx(new Choice("Hand","Discard",[Token(first)]));var r=t.BeginRequest("hand","Hand","Exhaust",1,1);Reject(()=>t.OpenRequest(r,[first]));});
Test("movement contradiction", () => {using var t=Tx(new Choice("Hand","Exhaust",[Token(first)]));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);t.CompleteRequest(r,[first]);Reject(()=>t.ObserveMove(first,"Draw",0));});
Test("duplicate result", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);t.CompleteRequest(r,[first]);Reject(()=>t.CompleteRequest(r,[first]));});
Test("missing result", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);Reject(()=>t.FinishAction());});
Test("missing request", () => {using var t=Tx(Choice("Hand",Token(first)));Reject(()=>t.FinishAction());});
Test("zero options does not consume next", () => {using var t=Tx(Choice("Hand",Token(first)));var e=t.BeginRequest("empty","Hand","unknown",1,1);t.OpenRequest(e,[]);t.CompleteRequest(e,[]);var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);t.CompleteRequest(r,[first]);t.FinishAction();});
Test("optional empty plan", () => {using var t=Tx(Choice("Hand"));var r=t.BeginRequest("optional","Hand","unknown",0,1);t.OpenRequest(r,[first]);t.CompleteRequest(r,[]);t.FinishAction();});
Test("ordered multi-selection", () => {using var t=Tx(Choice("Hand",Token(first),Token(distinct)));var r=t.BeginRequest("many","Hand","unknown",2,2);t.OpenRequest(r,[first,distinct]);Reject(()=>t.CompleteRequest(r,[distinct,first]));});
Test("multi-result is one request", () => {using var t=Tx(Choice("Hand",Token(first),Token(distinct)));var r=t.BeginRequest("many","Hand","unknown",2,2);t.OpenRequest(r,[first,distinct]);t.CompleteRequest(r,[first,distinct]);t.FinishAction();});
Test("nested completion order", () => {using var t=Tx(Choice("Hand",Token(first)),Choice("Hand",Token(distinct)));var r=t.BeginRequest("outer","Hand","unknown",1,1);t.OpenRequest(r,[first]);var n=t.BeginRequest("inner","Hand","unknown",1,1);t.OpenRequest(n,[distinct]);t.CompleteRequest(n,[distinct]);t.CompleteRequest(r,[first]);t.FinishAction();});
Test("async completion", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("async","Hand","unknown",1,1);t.OpenRequest(r,[first]);Task.Run(()=>t.CompleteRequest(r,[first])).GetAwaiter().GetResult();t.FinishAction();});
Test("late result after reset", () => {var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("late","Hand","unknown",1,1);t.OpenRequest(r,[first]);t.Dispose();Reject(()=>t.CompleteRequest(r,[first]));});
Test("exception retained", () => {using var t=Tx();t.Fault(new Exception("native failure"));Reject(()=>t.FinishAction());});
Test("source identity survives reordered options", () => {using var t=Tx(Choice("Hand",Token(second,1,0)));var r=t.BeginRequest("shuffled subset","Hand","unknown",1,1);t.OpenRequest(r,[first,second]);if(!ReferenceEquals(t.Select([second,first],1,1)[0],second))throw new Exception();t.CompleteRequest(r,[second]);t.FinishAction();});
Test("invalid option coordinate", () => {using var t=Tx(Choice("Hand",Token(first,0,2)));var r=t.BeginRequest("hand","Hand","unknown",1,1);Reject(()=>t.OpenRequest(r,[first,second]));});
Test("foreign request", () => {using var t=Tx();using var other=Tx();var r=other.BeginRequest("other","Hand","unknown",0,1);Reject(()=>t.CompleteRequest(r,[]));});
Test("cancelable required prompt", () => {using var t=Tx(Choice("Hand"));var r=t.BeginRequest("cancel","Hand","unknown",1,1,true);t.OpenRequest(r,[first]);t.Select([first],1,1);t.CompleteRequest(r,[]);if(!r.Cancelled)throw new Exception();t.FinishAction();});
Test("required prompt rejects empty", () => {using var t=Tx(Choice("Hand"));var r=t.BeginRequest("required","Hand","unknown",1,1);Reject(()=>t.OpenRequest(r,[first]));});
Test("combat end cancels unrequested plan", () => {using var t=Tx(Choice("Hand",Token(first)));t.FinishAction(combatEnded:true);});
Test("combat end cannot hide mismatch", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first,second]);Reject(()=>t.CompleteRequest(r,[second]));Reject(()=>t.FinishAction(combatEnded:true));});
Test("combat end cannot hide pending result", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("hand","Hand","unknown",1,1);t.OpenRequest(r,[first]);Reject(()=>t.FinishAction(combatEnded:true));});
Test("scalar null is empty", () => {using var t=Tx();var r=t.BeginRequest("scalar","Hand","unknown",1,1);t.OpenRequest(r,[]);t.CompleteRequest(r,[null!],singleCardResult:true);t.FinishAction();});
Test("scalar null cannot erase required target", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("scalar","Hand","unknown",1,1);t.OpenRequest(r,[first]);Reject(()=>t.CompleteRequest(r,[null!],singleCardResult:true));Reject(()=>t.FinishAction());});
Test("multi-card null rejected with diagnostic", () => {using var t=Tx();var r=t.BeginRequest("many","Hand","unknown",0,2);t.OpenRequest(r,[]);try {t.CompleteRequest(r,[null!]);throw new Exception("Expected rejection");}catch(InvalidOperationException e){if(!e.Message.Contains("<null>"))throw;}Reject(()=>t.FinishAction());});
Test("mixed null cannot disappear", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("many","Hand","unknown",1,2);t.OpenRequest(r,[first]);Reject(()=>t.CompleteRequest(r,[first,null!]));Reject(()=>t.FinishAction());});
Test("scalar rejects multiple objects", () => {using var t=Tx(Choice("Hand",Token(first),Token(distinct)));var r=t.BeginRequest("scalar","Hand","unknown",1,2);t.OpenRequest(r,[first,distinct]);Reject(()=>t.CompleteRequest(r,[first,distinct],singleCardResult:true));});
Test("scalar rejects mixed null", () => {using var t=Tx(Choice("Hand",Token(first)));var r=t.BeginRequest("scalar","Hand","unknown",1,1);t.OpenRequest(r,[first]);Reject(()=>t.CompleteRequest(r,[first,null!],singleCardResult:true));});
Console.WriteLine($"PASS {passed} transaction cases");
record Token(string CardId,int UpgradeLevel,string StateKey,int SourceOccurrence,int OptionOccurrence);
record Choice(string SourcePile,string Effect,Token[] Cards);
